// Generated by github.com/romshark/toki. DO NOT EDIT.

package tokibundle

import (
	"fmt"
	"io"
	"time"

	locales "github.com/go-playground/locales"
	locale "github.com/go-playground/locales/en"
	language "golang.org/x/text/language"
)

// This prevents the "imported and not used" error when some features are not used.
var (
	_ fmt.Formatter = nil
	_ time.Time

	tr_en  = locale.New()
	loc_en = language.MustParse("en")
)

type catalog_en struct{}

var writers_en = map[string]func(w io.Writer, args ...any) (int, error){
	msg174d508b7de4a66e: func(w io.Writer, args ...any) (written int, err error) {
		return wrs(w, "Flour site")
	},
	msg1837c1944267e92c: func(w io.Writer, args ...any) (written int, err error) {
		return wrs(w, "When baking gluten-free goods, it's typically best to mix a few different kinds of flours")
	},
	msg29f53e485d987b3a: func(w io.Writer, args ...any) (written int, err error) {
		return wrs(w, "Rice flour")
	},
	msg74b8f28e46dd53ca: func(w io.Writer, args ...any) (written int, err error) {
		return wrs(w, "Wheat flours")
	},
	msg7bb3ef92a7e3143: func(w io.Writer, args ...any) (written int, err error) {
		return wrs(w, "When it comes to wheat flours, there is a great variety and with varying levels of nutrition. The more of the grain left in the flour, the better. Stone-milled flours are not just a fad, but a sign that says that this flour likely has more fiber and nutrition")
	},
	msgadaaf2bd729300b7: func(w io.Writer, args ...any) (written int, err error) {
		return wrs(w, "Bake bread")
	},
	msgbbeadd7d919a7262: func(w io.Writer, args ...any) (written int, err error) {
		return wrs(w, "On this page I will collect a few of my favourite flour varieties")
	},
	msgccdcc7fa59d07e9: func(w io.Writer, args ...any) (written int, err error) {
		return wrs(w, "Spring wheat flour (aka bread flour)")
	},
	msgce17bb72c4cbde42: func(w io.Writer, args ...any) (written int, err error) {
		return wrs(w, "Graham flour")
	},
	msgd2b12e933df64c21: func(w io.Writer, args ...any) (written int, err error) {
		return wrs(w, "Almond flour")
	},
	msgd705fc92646475e1: func(w io.Writer, args ...any) (written int, err error) {
		return wrs(w, "Spelt flour")
	},
	msgda9447c71e9d623c: func(w io.Writer, args ...any) (written int, err error) {
		return wrs(w, "My flour lists")
	},
	msgdc9cd0d10c2be12: func(w io.Writer, args ...any) (written int, err error) {
		var n int
		n, err = io.WriteString(w, tr_en.FmtDateMedium(args[0].(time.Time)))
		if err != nil {
			return written, err
		}
		written += n
		n, err = wrs(w, " ")
		if err != nil {
			return written, err
		}
		written += n
		{
			s, _ := sv(args[1])
			n, err = wrs(w, s)
		}
		if err != nil {
			return written, err
		}
		written += n
		n, err = wrs(w, " proposed: ")
		if err != nil {
			return written, err
		}
		written += n
		{
			s, _ := sv(args[2])
			n, err = wrs(w, s)
		}
		if err != nil {
			return written, err
		}
		written += n
		return written, nil
	},
	msgddbcdfb79053245d: func(w io.Writer, args ...any) (written int, err error) {
		return wrs(w, "Gluten-free flours are important for allergy reasons and being able to make things for friends that won't kill them. They are also important for bread-baking.")
	},
	msge6f7796c88d8fbbc: func(w io.Writer, args ...any) (written int, err error) {
		return wrs(w, "Gluten-free flours")
	},
	msgf445564e16921617: func(w io.Writer, args ...any) (written int, err error) {
		return wrs(w, "Chickpea flour")
	},
}

func (catalog_en) Locale() language.Tag { return loc_en }

func (catalog_en) Translator() locales.Translator { return tr_en }

func (catalog_en) String(tik string, args ...any) string {
	b := poolBufGet()
	defer poolBufPut(b)
	f := writers_en[tik]
	if f == nil {
		_, _ = MissingTranslation(b, loc_en, tik, args...)
	} else {
		_, _ = f(b, args...)
	}
	return b.String()
}

func (catalog_en) Write(
	writer io.Writer, tik string, args ...any,
) (written int, err error) {
	f := writers_en[tik]
	if f == nil {
		return MissingTranslation(writer, loc_en, tik, args...)
	}
	return f(writer, args...)
}
